### ISSUE TITLE
Spammy environment errors when running server side.

### ISSUE THREAD

**Issue by NZKoz** [MindscapeHQ/raygun4java#26]
I get this error / info on startup:

```
INFO  Raygun4Java.environment - Couldn't access all environment data. If you are running in GAE or a restricted environment this is expected
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at sun.java2d.HeadlessGraphicsEnvironment.getMaximumWindowBounds(HeadlessGraphicsEnvironment.java:85) ~[na:1.8.0_40]
        at com.mindscapehq.raygun4java.core.messages.RaygunEnvironmentMessage.<init>(RaygunEnvironmentMessage.java:46) ~[read-api-0.0.1-42bc0ed.jar:na]
```

Indeed there is no X11DISPLAY variable set on my headless servers, that seems like the minority of cases so perhaps be more silent about that case?

**Comment by fundead** [comment]
Fixed in #32
